# Stage 3 - Macro regimes

- **Part 1: the baseline.** Four growth/inflation quadrants with simple rules, and a regression of the stock-bond
  correlation on growth and inflation. This is what PCA and clustering have to beat.
- **Part 2a: principal component analysis.** The 10 indicators reduced to a few factors, refitted every month on an
  expanding window, for real-time and revised data.
- **Part 2b: clustering.** K-Means and Gaussian mixtures on the factors, refitted every month, number of regimes
  chosen by BIC with data up to 2005.
- **Part 2c: clustering on growth and inflation kept separate.** The same methods on the two indices of part 1
  (and the CPI level), the design suggested by the diagnosis of part 2b.

- **Input:** `data/processed/` (from `02_clean.ipynb`)
- **Output:** `data/processed/baseline_regimes.csv`, `pca_scores.csv`, `pca_loadings_full.csv`, `pca_stability.csv`,
  `regimes_labels.csv`, `regimes_probabilities.csv`, `regimes_separation.csv`,
  `regimes_idx_labels.csv`, `regimes_idx_probabilities.csv`, `regimes_idx_separation.csv`
- **Target:** the SPY-TLT correlation over the next 3 months (main) and the next month (robustness)

Run from top to bottom in a fresh kernel (about 3 minutes: parts 2b and 2c refit many models every month).

In [1]:
import numpy as np
import pandas as pd

import config
import helpers

## 1. Load the data

In [2]:
macro = {
    "realtime": helpers.load_processed("macro_realtime_12m", index_col="date", parse_dates=True),
    "revised": helpers.load_processed("macro_revised_12m", index_col="date", parse_dates=True),
}
sb = helpers.load_processed("stock_bond_corr", index_col="date", parse_dates=True)

# what the regimes should explain, known only after month t:
# main = correlation over the next 3 months (t+1 to t+3); robustness = next month only (t+1).
# "current" = the same measure over the window that ends at t, already known at t.
TARGETS = {
    "3m": {"next": sb["spy_tlt_corr_3m"].shift(-3, freq="ME"), "current": sb["spy_tlt_corr_3m"]},
    "1m": {"next": sb["spy_tlt_corr"].shift(-1, freq="ME"), "current": sb["spy_tlt_corr"]},
}
corr = sb["spy_tlt_corr"]

ANALYSIS_START = "2006-01-31"   # same sample as the portfolios (all 4 ETFs from 2006)
print(macro["realtime"].shape, corr.shape)

(428, 10) (289,)

## 2. Growth and inflation indices

1. Each indicator is standardised with its **past only** (expanding mean and standard deviation, at least 36 months),
   so no future information enters.
2. Unemployment and claims get a minus sign: when they rise, growth is weaker.
3. z-scores are capped at ±3. Without the cap, COVID (claims +315% in May 2020) would dominate every average.
4. Growth index = average of the 7 growth and labour z-scores; inflation index = average of the 3 inflation z-scores.

In [3]:
GROWTH = ["indpro", "tcu", "retail", "housing", "payrolls", "unrate", "claims"]
INFLATION = ["cpi", "core_cpi", "ppi"]
SIGN = {"unrate": -1, "claims": -1}   # higher = weaker growth
MIN_HISTORY = 36
CAP = 3


def expanding_z(df):
    """z-score of each column using only the data up to that month."""
    mean = df.expanding(MIN_HISTORY).mean()
    std = df.expanding(MIN_HISTORY).std()
    return ((df - mean) / std).clip(-CAP, CAP)


indices = {}
for name, df in macro.items():
    z = expanding_z(df)
    for col, s in SIGN.items():
        z[col] = s * z[col]
    indices[name] = pd.DataFrame({"growth": z[GROWTH].mean(axis=1),
                                  "inflation": z[INFLATION].mean(axis=1)})

indices["realtime"].loc[["2008-06-30", "2008-12-31", "2020-04-30", "2022-06-30"]].round(2)

            growth  inflation
date
2008-06-30   -1.43       1.31
2008-12-31   -2.67      -1.26
2020-04-30   -1.52      -0.71
2022-06-30    0.75       3.00

## 3. Quadrants

Each month, growth and inflation are "high" when above the median of their own past (expanding, at least 24 months).

In [4]:
QUADRANTS = {(True, False): "goldilocks", (True, True): "overheating",
             (False, True): "stagflation", (False, False): "slowdown"}


def quadrants(idx):
    past_median = idx.expanding(24).median().shift(1)    # median of the past only
    high = idx > past_median
    labels = [QUADRANTS[(g, i)] for g, i in zip(high["growth"], high["inflation"])]
    return pd.Series(labels, index=idx.index).where(past_median.notna().all(axis=1))


regimes = pd.DataFrame({name: quadrants(idx) for name, idx in indices.items()}).loc[ANALYSIS_START:]
print("months per quadrant:")
print(regimes.apply(pd.Series.value_counts))

same = (regimes["realtime"] == regimes["revised"]).mean()
print(f"\nreal time and revised give the same quadrant in {same:.0%} of months")
print("months where they differ:")
print(regimes[regimes["realtime"] != regimes["revised"]])

months per quadrant:
             realtime  revised
goldilocks         53       47
overheating        48       48
slowdown           51       53
stagflation        96      100

real time and revised give the same quadrant in 96% of months
months where they differ:
               realtime      revised
date
2006-10-31  overheating  stagflation
2011-03-31   goldilocks  overheating
2014-06-30   goldilocks  overheating
2015-06-30   goldilocks     slowdown
2015-08-31   goldilocks     slowdown
2015-09-30   goldilocks     slowdown
2015-10-31   goldilocks     slowdown
2016-11-30     slowdown  stagflation
2019-04-30     slowdown  stagflation
2022-11-30  overheating  stagflation

## 4. Stock-bond correlation by quadrant

The quadrant known at the end of month t is compared with the correlation **after** t:
over the next 3 months (main) and the next month (robustness). That is what an investor deciding at t cares about.

In [5]:
rows = []
for h, tg in TARGETS.items():
    nxt = tg["next"].reindex(regimes.index)
    for name in regimes:
        df = pd.DataFrame({"quadrant": regimes[name], "next_corr": nxt}).dropna()
        g = df.groupby("quadrant")["next_corr"]
        rows.append(pd.DataFrame({"target": h, "data": name, "months": g.size(), "mean_corr": g.mean(),
                                  "share_positive": g.apply(lambda x: (x > 0).mean())}))
by_quadrant = pd.concat(rows).reset_index().set_index(["target", "data", "quadrant"])
by_quadrant.round(2)

                             months  mean_corr  share_positive
target data     quadrant
3m     realtime goldilocks       53      -0.42            0.08
                overheating      48      -0.29            0.23
                slowdown         51      -0.33            0.10
                stagflation      93      -0.12            0.39
       revised  goldilocks       47      -0.42            0.09
                overheating      48      -0.32            0.19
                slowdown         53      -0.34            0.09
                stagflation      97      -0.12            0.39
1m     realtime goldilocks       53      -0.42            0.08
                overheating      48      -0.27            0.23
                slowdown         51      -0.33            0.20
                stagflation      95      -0.11            0.39
       revised  goldilocks       47      -0.42            0.09
                overheating      48      -0.29            0.21
                slowdown         53      -0.35            0.17
                stagflation      99      -0.11            0.39

Are the differences real? Regression of the future correlation on two dummies (high growth, high inflation),
with Newey-West standard errors: monthly correlations are autocorrelated, and the 3-month targets of
consecutive months overlap.

In [6]:
for h, tg in TARGETS.items():
    for name in regimes:
        q = regimes[name]
        X = pd.DataFrame({"high_growth": q.isin(["goldilocks", "overheating"]).astype(float),
                          "high_inflation": q.isin(["overheating", "stagflation"]).astype(float)})[q.notna()]
        table, info = helpers.ols_hac(tg["next"].reindex(X.index).rename("next_corr"), X)
        print(f"\ntarget {h}, {name}: R2 = {info['r2']:.3f}, {info['nobs']} months, {info['lags']} lags")
        print(table.round(3))

target 3m, realtime: R2 = 0.140, 245 months, 4 lags
                 coef     se      t      p
const          -0.304  0.049 -6.170  0.000
high_growth    -0.136  0.069 -1.954  0.051
high_inflation  0.170  0.062  2.733  0.006

target 3m, revised: R2 = 0.142, 245 months, 4 lags
                 coef     se      t      p
const          -0.306  0.048 -6.402  0.000
high_growth    -0.146  0.069 -2.115  0.034
high_inflation  0.170  0.061  2.762  0.006

target 1m, realtime: R2 = 0.107, 247 months, 4 lags
                 coef     se      t      p
const          -0.308  0.048 -6.486  0.000
high_growth    -0.132  0.067 -1.963  0.050
high_inflation  0.188  0.063  2.996  0.003

target 1m, revised: R2 = 0.110, 247 months, 4 lags
                 coef     se     t      p
const          -0.318  0.045 -7.09  0.000
high_growth    -0.135  0.068 -2.00  0.045
high_inflation  0.195  0.061  3.23  0.001

## 5. Regression on the indices

Same idea with the continuous indices instead of the quadrants, three models:
- **A**: future correlation on growth and inflation;
- **B**: adds the current correlation. Correlations are persistent, so the question is whether
  macro data explains anything **beyond** what the current correlation already tells;
- **C**: adds the **level** of CPI inflation (12-month change, in %). The indices say whether inflation is high
  *relative to its own past*; the literature suggests the absolute level matters (the stock-bond correlation
  tends to turn positive when inflation is above roughly 2.5-3%). Test decided before looking at its result.

In [7]:
def model_table(X, cpi_level, label):
    """Models A, B and C for both targets. Each cell: coefficient (p-value)."""
    rows = []
    for h, tg in TARGETS.items():
        y = tg["next"].reindex(X.index).rename("next_corr")
        specs = {"A": X,
                 "B": X.join(tg["current"].reindex(X.index).rename("current_corr")),
                 "C": X.join(cpi_level.reindex(X.index).rename("cpi_level"))}
        for m, R in specs.items():
            table, info = helpers.ols_hac(y, R)
            row = {"data": label, "target": h, "model": m, "R2": round(info["r2"], 3), "months": info["nobs"]}
            row.update({v: f"{table.loc[v, 'coef']:.3f} ({table.loc[v, 'p']:.3f})" for v in table.index[1:]})
            rows.append(row)
    return pd.DataFrame(rows).set_index(["data", "target", "model"])


index_results = pd.concat([model_table(indices[name].loc[ANALYSIS_START:], macro[name]["cpi"], name)
                           for name in indices])
index_results

                          R2  months          growth       inflation  \
data     target model
realtime 3m     A      0.090     245  -0.047 (0.257)   0.089 (0.006)
                B      0.440     245  -0.035 (0.145)   0.036 (0.074)
                C      0.108     245  -0.036 (0.406)  -0.081 (0.486)
         1m     A      0.055     247  -0.032 (0.461)   0.083 (0.014)
                B      0.291     247  -0.023 (0.367)   0.043 (0.026)
                C      0.066     247  -0.022 (0.631)  -0.078 (0.508)
revised  3m     A      0.091     245  -0.046 (0.273)   0.089 (0.006)
                B      0.439     245  -0.033 (0.168)   0.035 (0.078)
                C      0.106     245  -0.035 (0.433)  -0.068 (0.571)
         1m     A      0.055     247  -0.031 (0.488)   0.083 (0.014)
                B      0.291     247  -0.022 (0.402)   0.043 (0.028)
                C      0.065     247  -0.020 (0.669)  -0.070 (0.569)

                        current_corr      cpi_level
data     target model
realtime 3m     A                NaN            NaN
                B      0.636 (0.000)            NaN
                C                NaN  0.107 (0.100)
         1m     A                NaN            NaN
                B      0.503 (0.000)            NaN
                C                NaN  0.102 (0.127)
revised  3m     A                NaN            NaN
                B      0.636 (0.000)            NaN
                C                NaN  0.099 (0.144)
         1m     A                NaN            NaN
                B      0.503 (0.000)            NaN
                C                NaN  0.096 (0.164)

## 6. Save

In [8]:
baseline = pd.concat({f"{name}_{col}": indices[name][col].loc[ANALYSIS_START:]
                      for name in indices for col in ["growth", "inflation"]}, axis=1)
baseline["realtime_quadrant"] = regimes["realtime"]
baseline["revised_quadrant"] = regimes["revised"]
path = helpers.save_processed(baseline, "baseline_regimes")
print(f"saved {path.name}: {baseline.shape[0]} rows x {baseline.shape[1]} columns")

saved baseline_regimes.csv: 248 rows x 6 columns

# Part 2a - Principal component analysis

PCA turns the 10 standardised indicators into a few uncorrelated factors. It is done three ways:

1. **Full sample** - only to describe and name the factors. It uses all data up to 2026, so it is never used for decisions.
2. **Expanding window** - each month, PCA is refitted on the data known up to that month, and the month gets its factor scores.
   These are the scores the clustering and the portfolios will use.
3. For **real-time and revised data**, and for **12-month and 3-month changes** (robustness check).

The input is the same as in the baseline: z-scores computed with past data only, unemployment and claims with a minus sign
(higher = stronger economy), capped at ±3.

In [9]:
from sklearn.decomposition import PCA

macro_3m = {
    "realtime": helpers.load_processed("macro_realtime_3m", index_col="date", parse_dates=True),
    "revised": helpers.load_processed("macro_revised_3m", index_col="date", parse_dates=True),
}


def signed_z(df):
    """Expanding z-scores (past only, capped), with unemployment and claims flipped."""
    z = expanding_z(df)
    for col, s in SIGN.items():
        z[col] = s * z[col]
    return z.dropna()          # PCA needs all 10 indicators in a month


Z = {(name, "12m"): signed_z(macro[name]) for name in macro}
Z.update({(name, "3m"): signed_z(macro_3m[name]) for name in macro_3m})
for key, z in Z.items():
    print(key, "complete months:", z.index[0].date(), "->", z.index[-1].date(), f"({len(z)})")

('realtime', '12m') complete months: 1996-01-31 -> 2026-08-31 (368)
('revised', '12m') complete months: 1996-01-31 -> 2026-08-31 (368)
('realtime', '3m') complete months: 1996-01-31 -> 2026-08-31 (368)
('revised', '3m') complete months: 1996-01-31 -> 2026-08-31 (368)

## 2a.1 Full-sample PCA: how many factors, and what they mean

Rules of thumb for the number of components: keep those with an eigenvalue above 1 (each explains more than one
indicator's worth of variance, i.e. more than 10% here), or enough to explain about 75% of the variance.

In [10]:
N_PC = 3   # components saved; the main analysis uses the first 2


def align_signs(components, columns):
    """PCA signs are arbitrary. Fix them: PC1 positive on payrolls, PC2 positive on CPI, PC3 positive on PPI."""
    anchors = ["payrolls", "cpi", "ppi"]
    comps = components.copy()
    for k in range(min(len(comps), len(anchors))):
        if comps[k, columns.get_loc(anchors[k])] < 0:
            comps[k] = -comps[k]
    return comps


full = {}
for key, z in Z.items():
    pca = PCA().fit(z)
    comps = align_signs(pca.components_, z.columns)
    full[key] = {"pca": pca, "loadings": pd.DataFrame(comps[:N_PC].T, index=z.columns,
                                                      columns=[f"pc{k+1}" for k in range(N_PC)])}

variance = pd.DataFrame({f"{n}_{h}": full[(n, h)]["pca"].explained_variance_ratio_[:5] for n, h in full},
                        index=[f"pc{k+1}" for k in range(5)])
print("share of variance explained:")
print(variance.round(3))
print("\ncumulative:")
print(variance.cumsum().round(2))
print("\neigenvalues, real time 12m:", full[("realtime", "12m")]["pca"].explained_variance_.round(2)[:5])

share of variance explained:
     realtime_12m  revised_12m  realtime_3m  revised_3m
pc1         0.482        0.479        0.354       0.363
pc2         0.212        0.225        0.212       0.223
pc3         0.120        0.106        0.128       0.119
pc4         0.080        0.079        0.097       0.097
pc5         0.039        0.039        0.063       0.059

cumulative:
     realtime_12m  revised_12m  realtime_3m  revised_3m
pc1          0.48         0.48         0.35        0.36
pc2          0.69         0.70         0.57        0.59
pc3          0.81         0.81         0.69        0.70
pc4          0.89         0.89         0.79        0.80
pc5          0.93         0.93         0.85        0.86

eigenvalues, real time 12m: [6.25 2.75 1.56 1.04 0.51]

In [11]:
print("loadings, real time 12m:")
full[("realtime", "12m")]["loadings"].round(2)

loadings, real time 12m:

           pc1   pc2   pc3
indpro    0.36 -0.15  0.02
tcu       0.25 -0.02 -0.40
retail    0.25 -0.30  0.37
housing   0.15 -0.36  0.24
payrolls  0.36 -0.15 -0.37
unrate    0.39 -0.22 -0.14
claims    0.39 -0.25  0.11
cpi       0.34  0.55  0.02
core_cpi  0.19  0.29 -0.45
ppi       0.37  0.49  0.52

## 2a.2 Expanding-window PCA

For each month t from the point where at least 60 complete months are available:
fit PCA on the z-scores up to t, fix the signs, and compute the scores of month t.
Nothing after t is used. The loadings of every refit are kept, to check how stable the factors are.

In [12]:
MIN_PCA_HISTORY = 60


def expanding_pca(z, n=N_PC, min_history=MIN_PCA_HISTORY):
    scores, loadings, explained = {}, {}, {}
    for i in range(min_history, len(z) + 1):
        window = z.iloc[:i]
        t = window.index[-1]
        pca = PCA(n_components=n).fit(window)
        comps = align_signs(pca.components_, z.columns)
        centred = window.iloc[-1] - pca.mean_
        scores[t] = comps @ centred.to_numpy()
        loadings[t] = comps
        explained[t] = pca.explained_variance_ratio_
    cols = [f"pc{k+1}" for k in range(n)]
    return (pd.DataFrame(scores, index=cols).T,
            loadings,
            pd.DataFrame(explained, index=cols).T)


expanding = {key: expanding_pca(z) for key, z in Z.items()}
for key, (sc, _, ex) in expanding.items():
    print(key, "scores from", sc.index[0].date(), "| variance of last fit:", ex.iloc[-1].round(2).to_list())

('realtime', '12m') scores from 2000-12-31 | variance of last fit: [0.48, 0.21, 0.12]
('revised', '12m') scores from 2000-12-31 | variance of last fit: [0.48, 0.22, 0.11]
('realtime', '3m') scores from 2000-12-31 | variance of last fit: [0.35, 0.21, 0.13]
('revised', '3m') scores from 2000-12-31 | variance of last fit: [0.36, 0.22, 0.12]

## 2a.3 Are the factors stable over time?

Similarity between the loadings of each monthly refit and the full-sample loadings (cosine similarity:
1 = same direction, 0 = unrelated). If the factors keep their meaning over time, the values stay close to 1.

In [13]:
def cosine(a, b):
    return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b)))


stability = {}
for key, (sc, loads, ex) in expanding.items():
    ref = full[key]["loadings"].T.to_numpy()
    stability[key] = pd.DataFrame({t: [cosine(L[k], ref[k]) for k in range(N_PC)] for t, L in loads.items()},
                                  index=[f"pc{k+1}" for k in range(N_PC)]).T

for key, st in stability.items():
    s = st.loc[ANALYSIS_START:]
    print(f"{key}: similarity with full-sample loadings from 2006, min / median:",
          s.min().round(2).to_dict(), "/", s.median().round(2).to_dict())

('realtime', '12m'): similarity with full-sample loadings from 2006, min / median: {'pc1': 0.76, 'pc2': 0.84, 'pc3': 0.77} / {'pc1': 0.96, 'pc2': 0.96, 'pc3': 0.91}
('revised', '12m'): similarity with full-sample loadings from 2006, min / median: {'pc1': 0.53, 'pc2': 0.55, 'pc3': 0.63} / {'pc1': 0.95, 'pc2': 0.94, 'pc3': 0.77}
('realtime', '3m'): similarity with full-sample loadings from 2006, min / median: {'pc1': 0.56, 'pc2': 0.58, 'pc3': 0.82} / {'pc1': 0.96, 'pc2': 0.98, 'pc3': 0.93}
('revised', '3m'): similarity with full-sample loadings from 2006, min / median: {'pc1': -0.26, 'pc2': -0.4, 'pc3': 0.76} / {'pc1': 0.93, 'pc2': 0.95, 'pc3': 0.9}

In [14]:
# how much does hindsight change the scores? expanding-window vs full-sample scores, from 2006
for key, (sc, _, _) in expanding.items():
    z = Z[key].loc[sc.index]
    full_scores = (z - full[key]["pca"].mean_) @ full[key]["loadings"]
    c = [sc[f"pc{k}"].loc[ANALYSIS_START:].corr(full_scores[f"pc{k}"].loc[ANALYSIS_START:]) for k in (1, 2, 3)]
    print(f"{key}: correlation expanding vs full-sample scores (pc1, pc2, pc3):", np.round(c, 2))

('realtime', '12m'): correlation expanding vs full-sample scores (pc1, pc2, pc3): [0.98 0.96 0.91]
('revised', '12m'): correlation expanding vs full-sample scores (pc1, pc2, pc3): [0.98 0.82 0.84]
('realtime', '3m'): correlation expanding vs full-sample scores (pc1, pc2, pc3): [0.94 0.9  0.93]
('revised', '3m'): correlation expanding vs full-sample scores (pc1, pc2, pc3): [0.92 0.61 0.92]

## 2a.4 Real time against revised

Same horizon, two data versions: how close are the factor scores, and when do they differ most?

In [15]:
for h in ["12m", "3m"]:
    a, b = expanding[("realtime", h)][0].loc[ANALYSIS_START:], expanding[("revised", h)][0].loc[ANALYSIS_START:]
    print(f"\n{h}: correlation real time vs revised:", {c: round(a[c].corr(b[c]), 3) for c in a})
    print(f"{h}: mean absolute difference:", (a - b).abs().mean().round(2).to_dict())

diff = (expanding[("realtime", "12m")][0] - expanding[("revised", "12m")][0]).loc[ANALYSIS_START:]
print("\nlargest real time - revised gaps on pc1 (12m):")
print(diff["pc1"].abs().sort_values(ascending=False).head(6).round(2))
print("\npc1 and pc2 in 2008, real time vs revised (12m):")
print(pd.concat({"realtime": expanding[("realtime", "12m")][0], "revised": expanding[("revised", "12m")][0]},
                axis=1).loc["2008-03-31":"2009-03-31", (slice(None), ["pc1", "pc2"])].round(2))

12m: correlation real time vs revised: {'pc1': np.float64(0.937), 'pc2': np.float64(0.882), 'pc3': np.float64(0.96)}
12m: mean absolute difference: {'pc1': 0.37, 'pc2': 0.38, 'pc3': 0.28}

3m: correlation real time vs revised: {'pc1': np.float64(0.861), 'pc2': np.float64(0.481), 'pc3': np.float64(0.96)}
3m: mean absolute difference: {'pc1': 0.48, 'pc2': 0.62, 'pc3': 0.29}

largest real time - revised gaps on pc1 (12m):
2008-09-30    7.55
2008-10-31    7.43
2008-08-31    6.00
2008-07-31    4.20
2008-06-30    2.91
2008-11-30    2.73
Name: pc1, dtype: float64

pc1 and pc2 in 2008, real time vs revised (12m):
           realtime       revised
                pc1   pc2     pc1   pc2
2008-03-31     1.07  3.13   -0.33  2.97
2008-04-30     1.04  3.96   -0.95  3.43
2008-05-31     0.80  3.73   -1.17  3.43
2008-06-30     0.74  4.49   -2.17  3.86
2008-07-31     1.42  4.79   -2.78  4.18
2008-08-31     1.83  5.34   -4.17  3.86
2008-09-30     1.75  5.94   -5.80  2.54
2008-10-31     0.83  6.32   -6.60  0.89
2008-11-30    -3.23  4.60   -5.95 -0.62
2008-12-31    -6.12  0.52   -5.56 -3.27
2009-01-31    -7.06 -0.29   -6.14 -3.95
2009-02-28    -7.59 -0.34   -6.66 -3.50
2009-03-31    -7.78 -0.38   -7.04 -3.18

## 2a.5 Do the factors explain the stock-bond correlation?

Same three models as in the baseline (section 5), with the first two factors instead of the growth and
inflation indices.

In [16]:
pca_results = pd.concat([
    model_table(expanding[(n, h)][0][["pc1", "pc2"]].loc[ANALYSIS_START:], macro[n]["cpi"], f"{n} {h}")
    for n, h in [("realtime", "12m"), ("revised", "12m"), ("realtime", "3m"), ("revised", "3m")]])
pca_results

                              R2  months             pc1             pc2  \
data         target model
realtime 12m 3m     A      0.076     245  -0.005 (0.544)   0.053 (0.060)
                    B      0.441     245  -0.008 (0.218)   0.024 (0.088)
                    C      0.174     245  -0.059 (0.000)  -0.054 (0.181)
             1m     A      0.042     247  -0.002 (0.859)   0.047 (0.107)
                    B      0.289     247  -0.003 (0.598)   0.025 (0.113)
                    C      0.106     247  -0.054 (0.001)  -0.058 (0.160)
revised 12m  3m     A      0.095     245  -0.009 (0.490)   0.062 (0.023)
                    B      0.439     245  -0.009 (0.227)   0.025 (0.118)
                    C      0.114     245  -0.020 (0.196)   0.010 (0.842)
             1m     A      0.063     247  -0.004 (0.746)   0.059 (0.029)
                    B      0.293     247  -0.005 (0.582)   0.031 (0.050)
                    C      0.069     247  -0.012 (0.472)   0.024 (0.633)
realtime 3m  3m     A      0.033     245   0.014 (0.111)   0.033 (0.142)
                    B      0.427     245   0.004 (0.490)   0.010 (0.462)
                    C      0.095     245  -0.008 (0.525)   0.007 (0.761)
             1m     A      0.022     247   0.019 (0.082)   0.027 (0.233)
                    B      0.281     247   0.008 (0.259)   0.011 (0.379)
                    C      0.060     247  -0.003 (0.861)   0.003 (0.906)
revised 3m   3m     A      0.083     245  -0.003 (0.745)   0.065 (0.003)
                    B      0.428     245   0.002 (0.719)   0.014 (0.439)
                    C      0.126     245  -0.010 (0.332)   0.047 (0.039)
             1m     A      0.067     247   0.003 (0.802)   0.067 (0.002)
                    B      0.291     247   0.003 (0.674)   0.030 (0.028)
                    C      0.088     247  -0.003 (0.791)   0.051 (0.027)

                            current_corr      cpi_level
data         target model
realtime 12m 3m     A                NaN            NaN
                    B      0.642 (0.000)            NaN
                    C                NaN  0.146 (0.000)
             1m     A                NaN            NaN
                    B      0.510 (0.000)            NaN
                    C                NaN  0.143 (0.000)
revised 12m  3m     A                NaN            NaN
                    B      0.635 (0.000)            NaN
                    C                NaN  0.059 (0.166)
             1m     A                NaN            NaN
                    B      0.499 (0.000)            NaN
                    C                NaN  0.041 (0.362)
realtime 3m  3m     A                NaN            NaN
                    B      0.657 (0.000)            NaN
                    C                NaN  0.053 (0.003)
             1m     A                NaN            NaN
                    B      0.520 (0.000)            NaN
                    C                NaN  0.050 (0.010)
revised 3m   3m     A                NaN            NaN
                    B      0.645 (0.000)            NaN
                    C                NaN  0.039 (0.011)
             1m     A                NaN            NaN
                    B      0.496 (0.000)            NaN
                    C                NaN  0.034 (0.049)

## 2a.6 Save

- `pca_scores.csv`: expanding-window scores, one column per data version, horizon and factor
- `pca_loadings_full.csv`: full-sample loadings (to describe the factors in the paper)
- `pca_stability.csv`: similarity of each monthly refit with the full-sample loadings

In [17]:
scores_out = pd.concat({f"{n}_{h}": expanding[(n, h)][0] for n, h in expanding}, axis=1)
scores_out.columns = [f"{a}_{b}" for a, b in scores_out.columns]
loadings_out = pd.concat({f"{n}_{h}": full[(n, h)]["loadings"] for n, h in full}, axis=1)
loadings_out.columns = [f"{a}_{b}" for a, b in loadings_out.columns]
stability_out = pd.concat({f"{n}_{h}": stability[(n, h)] for n, h in stability}, axis=1)
stability_out.columns = [f"{a}_{b}" for a, b in stability_out.columns]

for df, name in [(scores_out.rename_axis("date"), "pca_scores"),
                 (loadings_out.rename_axis("indicator"), "pca_loadings_full"),
                 (stability_out.rename_axis("date"), "pca_stability")]:
    path = helpers.save_processed(df, name)
    print(f"saved {path.name}: {df.shape[0]} rows x {df.shape[1]} columns")

saved pca_scores.csv: 309 rows x 12 columns
saved pca_loadings_full.csv: 10 rows x 12 columns
saved pca_stability.csv: 309 rows x 12 columns

# Part 2b - Clustering: regimes found by the data

The factors from part 2a are grouped into regimes with two methods from the course:
- **K-Means**: each month belongs to exactly one regime (the closest centre);
- **Gaussian mixture (GMM)**: each regime is a bell-shaped cloud, and each month gets a **probability**
  of belonging to each regime. These probabilities are what the portfolio will use.

As for PCA, the models are **refitted every month on the data known up to that month** (expanding window).

Choices, all fixed before looking at the stock-bond results:
- **Features**: PC1 and PC2 (main). Variant: PC1, PC2 and the level of CPI inflation (the test from section 5).
  Each refit standardises the features on its own window.
- **Number of regimes**: chosen by BIC on the data available at the end of 2005, the last month before the
  evaluation sample, so the choice uses no future information. The full-sample BIC is shown as a check,
  and 2 and 4 regimes are run as robustness (4 = same number as the quadrants, a like-for-like comparison).
- **Labels over time**: a refit can call the same regime "1" one month and "2" the next. Each refit starts
  from the previous centres and its regimes are matched to the previous ones (the pairing with the smallest
  total distance between centres), so a regime keeps its label over time.

In [18]:
from itertools import permutations

from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler

pca_scores = expanding   # from part 2a: {(data, horizon): (scores, loadings, explained)}


def features(data, horizon, with_cpi=False):
    X = pca_scores[(data, horizon)][0][["pc1", "pc2"]].copy()
    if with_cpi:
        X["cpi_level"] = macro[data]["cpi"].reindex(X.index)
    return X.dropna()

## 2b.1 How many regimes? BIC

BIC rewards a model that fits the data well and penalises extra regimes. Lower is better.
Rule: the smallest number of regimes (at least 2) whose BIC is within 10 of the lowest BIC. A difference
below 10 is not "strong evidence" for the bigger model, so the simpler one is kept.

In [19]:
def bic_curve(X, ks=range(1, 7)):
    Xs = StandardScaler().fit_transform(X.to_numpy())
    return pd.Series({k: GaussianMixture(k, covariance_type="full", n_init=10,
                                         random_state=config.RANDOM_SEED).fit(Xs).bic(Xs) for k in ks})


def choose_k(bic, threshold=10):
    candidates = bic[bic.index >= 2]
    return int(candidates[candidates <= candidates.min() + threshold].index.min())


bic_table = {}
for data, horizon in [("realtime", "12m"), ("revised", "12m"), ("realtime", "3m"), ("revised", "3m")]:
    X = features(data, horizon)
    for period, Xp in [("up to 2005", X.loc[:"2005"]), ("full sample", X)]:
        b = bic_curve(Xp)
        bic_table[(f"{data} {horizon}", period)] = {**b.round(0).to_dict(), "chosen k": choose_k(b), "months": len(Xp)}
bic_table = pd.DataFrame(bic_table).T
bic_table

                               1       2       3       4       5       6  \
realtime 12m up to 2005    324.0   307.0   290.0   285.0   295.0   309.0
             full sample  1751.0  1592.0  1597.0  1566.0  1553.0  1555.0
revised 12m  up to 2005    310.0   273.0   260.0   256.0   250.0   250.0
             full sample  1723.0  1671.0  1534.0  1506.0  1513.0  1517.0
realtime 3m  up to 2005    359.0   349.0   356.0   369.0   380.0   384.0
             full sample  1780.0  1614.0  1612.0  1631.0  1636.0  1659.0
revised 3m   up to 2005    330.0   327.0   334.0   346.0   354.0   368.0
             full sample  1723.0  1623.0  1578.0  1596.0  1613.0  1635.0

                          chosen k  months
realtime 12m up to 2005        3.0    61.0
             full sample       5.0   309.0
revised 12m  up to 2005        4.0    61.0
             full sample       4.0   309.0
realtime 3m  up to 2005        2.0    61.0
             full sample       2.0   309.0
revised 3m   up to 2005        2.0    61.0
             full sample       3.0   309.0

In [20]:
K_MAIN = int(bic_table.loc[("realtime 12m", "up to 2005"), "chosen k"])   # real-time data, known at the end of 2005
print("number of regimes used:", K_MAIN)

number of regimes used: 3

## 2b.2 Expanding-window clustering

From the month with at least 60 months of factor scores: fit on the window, standardise, start from the
previous centres, match labels to the previous fit, and assign the last month.

In [21]:
MIN_CLUSTER_HISTORY = 60


def match_labels(new_centres, old_centres):
    """Order of the new regimes that best matches the old ones (smallest total distance)."""
    k = len(new_centres)
    best = min(permutations(range(k)),
               key=lambda p: sum(np.linalg.norm(new_centres[p[j]] - old_centres[j]) for j in range(k)))
    return list(best)   # best[j] = new regime that becomes regime j


def expanding_clusters(X, k, method):
    labels, probs, centres_path = {}, {}, {}
    old = None                                   # previous centres, in original feature units
    for i in range(MIN_CLUSTER_HISTORY, len(X) + 1):
        window = X.iloc[:i]
        t = window.index[-1]
        scaler = StandardScaler().fit(window.to_numpy())
        Xs = scaler.transform(window.to_numpy())
        init = None if old is None else scaler.transform(old)
        if method == "kmeans":
            model = KMeans(k, init=init if init is not None else "k-means++",
                           n_init=1 if init is not None else 10, random_state=config.RANDOM_SEED).fit(Xs)
            centres = model.cluster_centers_
        else:
            model = GaussianMixture(k, covariance_type="full", means_init=init,
                                    n_init=1 if init is not None else 10, random_state=config.RANDOM_SEED).fit(Xs)
            centres = model.means_
        centres = scaler.inverse_transform(centres)
        order = list(range(k)) if old is None else match_labels(centres, old)
        old = centres[order]
        last = Xs[-1:]
        if method == "kmeans":
            labels[t] = order.index(int(model.predict(last)[0]))
        else:
            p = model.predict_proba(last)[0][order]
            probs[t] = p
            labels[t] = int(np.argmax(p))
        centres_path[t] = old.copy()
    labels = pd.Series(labels, name="regime")
    probs = pd.DataFrame(probs, index=[f"p{j}" for j in range(k)]).T if probs else None
    return labels, probs, centres_path, old


RUNS = {}   # name -> (data, horizon, with_cpi, k)
for data in ["realtime", "revised"]:
    for k in sorted({2, K_MAIN, 4}):
        RUNS[f"{data}_12m_k{k}"] = (data, "12m", False, k)
    RUNS[f"{data}_3m_k{K_MAIN}"] = (data, "3m", False, K_MAIN)
    RUNS[f"{data}_12m_cpi_k{K_MAIN}"] = (data, "12m", True, K_MAIN)

clusters = {}
for name, (data, horizon, with_cpi, k) in RUNS.items():
    X = features(data, horizon, with_cpi)
    for method in ["kmeans", "gmm"]:
        clusters[(name, method)] = expanding_clusters(X, k, method)
    print(f"{name}: labels from {clusters[(name, 'gmm')][0].index[0].date()}")

realtime_12m_k2: labels from 2005-11-30
realtime_12m_k3: labels from 2005-11-30
realtime_12m_k4: labels from 2005-11-30
realtime_3m_k3: labels from 2005-11-30
realtime_12m_cpi_k3: labels from 2005-11-30
revised_12m_k2: labels from 2005-11-30
revised_12m_k3: labels from 2005-11-30
revised_12m_k4: labels from 2005-11-30
revised_3m_k3: labels from 2005-11-30
revised_12m_cpi_k3: labels from 2005-11-30

## 2b.3 What are the regimes?

Each regime of the main run described by its average factors, CPI inflation, growth index and how long it
usually lasts. Regimes are then named from these averages.

In [22]:
MAIN = f"realtime_12m_k{K_MAIN}"


def describe(name, method):
    data, horizon, with_cpi, k = RUNS[name]
    lab = clusters[(name, method)][0].loc[ANALYSIS_START:]
    X = features(data, horizon, True).reindex(lab.index)
    df = X.assign(growth=indices[data]["growth"].reindex(lab.index),
                  inflation=indices[data]["inflation"].reindex(lab.index), regime=lab)
    runs = (lab != lab.shift()).cumsum()
    duration = lab.groupby(runs).size().groupby(lab.groupby(runs).first()).mean()
    out = df.groupby("regime").mean().round(2)
    out.insert(0, "months", lab.value_counts().sort_index())
    out["avg duration (months)"] = duration.round(1)
    return out


for method in ["gmm", "kmeans"]:
    print(f"\n{MAIN}, {method}:")
    print(describe(MAIN, method))

switches = {m: int((clusters[(MAIN, m)][0].loc[ANALYSIS_START:].diff() != 0).sum() - 1) for m in ["gmm", "kmeans"]}
print("\nregime changes from 2006:", switches)

realtime_12m_k3, gmm:
        months   pc1   pc2  cpi_level  growth  inflation  \
regime
0           66  1.42  0.21       3.17    0.07       0.42
1          164  0.93 -0.02       2.56    0.04       0.01
2           18 -6.75 -0.35      -0.13   -2.55      -1.85

        avg duration (months)
regime
0                         4.7
1                        12.6
2                         9.0

realtime_12m_k3, kmeans:
        months   pc1   pc2  cpi_level  growth  inflation  \
regime
0          149  0.67 -0.73       2.03    0.10      -0.34
1           73  2.34  1.63       4.33    0.09       1.19
2           26 -5.63 -0.20       0.35   -2.16      -1.50

        avg duration (months)
regime
0                        13.5
1                         6.6
2                         8.7

regime changes from 2006: {'gmm': 28, 'kmeans': 24}

## 2b.4 Do the regimes separate the stock-bond correlation?

For every run: the average future correlation in each regime, and a regression of the future correlation on
regime dummies (Newey-West). The Wald test asks whether the regimes differ at all; R² says how much they explain.
The quadrants of part 1 are the benchmark.

In [23]:
def regime_test(labels, target):
    y = TARGETS[target]["next"].reindex(labels.index).rename("next_corr")
    dummies = pd.get_dummies(labels, prefix="r", dtype=float).iloc[:, 1:]   # first regime = reference
    table, info = helpers.ols_hac(y, dummies)
    stat, p = helpers.wald_test(table, info, list(dummies.columns))
    means = y.groupby(labels).mean()
    return {"R2": round(info["r2"], 3), "Wald p": round(p, 4), "months": info["nobs"],
            "corr by regime": " / ".join(f"{m:.2f}" for m in means)}


rows = {}
for target in ["3m", "1m"]:
    for name in RUNS:
        for method in ["gmm", "kmeans"]:
            rows[(target, name, method)] = regime_test(clusters[(name, method)][0].loc[ANALYSIS_START:], target)
    for data in ["realtime", "revised"]:
        rows[(target, f"{data} quadrants", "rules")] = regime_test(
            regimes[data].map({"goldilocks": 0, "overheating": 1, "slowdown": 2, "stagflation": 3}), target)
separation = pd.DataFrame(rows).T
separation.index.names = ["target", "run", "method"]
separation

                                      R2  Wald p months  \
target run                 method
3m     realtime_12m_k2     gmm     0.038  0.0422    245
                           kmeans    0.0   0.872    245
       realtime_12m_k3     gmm     0.003  0.5166    245
                           kmeans  0.024  0.4117    245
       realtime_12m_k4     gmm     0.263     0.0    245
                           kmeans  0.024  0.0002    245
       realtime_3m_k3      gmm     0.187     0.0    245
                           kmeans  0.018  0.0356    245
       realtime_12m_cpi_k3 gmm     0.117  0.0017    245
                           kmeans  0.004  0.8724    245
       revised_12m_k2      gmm       0.0  0.9137    245
                           kmeans  0.002  0.4878    245
       revised_12m_k3      gmm     0.009  0.6223    245
                           kmeans  0.028  0.1518    245
       revised_12m_k4      gmm      0.08  0.0274    245
                           kmeans  0.019  0.4617    245
       revised_3m_k3       gmm     0.103    0.01    245
                           kmeans  0.016   0.026    245
       revised_12m_cpi_k3  gmm     0.051  0.0242    245
                           kmeans  0.024  0.3963    245
       realtime quadrants  rules   0.144  0.0032    245
       revised quadrants   rules    0.15  0.0028    245
1m     realtime_12m_k2     gmm     0.007   0.297    247
                           kmeans  0.001  0.6477    247
       realtime_12m_k3     gmm     0.008  0.2128    247
                           kmeans  0.013  0.4151    247
       realtime_12m_k4     gmm     0.165  0.0001    247
                           kmeans  0.012  0.0075    247
       realtime_3m_k3      gmm     0.129  0.0002    247
                           kmeans  0.018  0.0179    247
       realtime_12m_cpi_k3 gmm     0.065   0.009    247
                           kmeans  0.003  0.8066    247
       revised_12m_k2      gmm     0.003    0.34    247
                           kmeans  0.007  0.0942    247
       revised_12m_k3      gmm     0.003  0.4025    247
                           kmeans  0.018  0.0549    247
       revised_12m_k4      gmm     0.064  0.0262    247
                           kmeans  0.015  0.3016    247
       revised_3m_k3       gmm     0.067  0.0106    247
                           kmeans  0.017  0.0834    247
       revised_12m_cpi_k3  gmm     0.015  0.2563    247
                           kmeans  0.021   0.164    247
       realtime quadrants  rules   0.109  0.0028    247
       revised quadrants   rules   0.114   0.002    247

                                                  corr by regime
target run                 method
3m     realtime_12m_k2     gmm                     -0.30 / -0.16
                           kmeans                  -0.25 / -0.26
       realtime_12m_k3     gmm             -0.27 / -0.25 / -0.32
                           kmeans          -0.30 / -0.19 / -0.25
       realtime_12m_k4     gmm      -0.36 / 0.02 / -0.16 / -0.37
                           kmeans  -0.30 / -0.40 / -0.19 / -0.25
       realtime_3m_k3      gmm             -0.11 / -0.40 / -0.37
                           kmeans          -0.28 / -0.22 / -0.38
       realtime_12m_cpi_k3 gmm             -0.23 / -0.36 / -0.09
                           kmeans          -0.28 / -0.24 / -0.24
       revised_12m_k2      gmm                     -0.27 / -0.26
                           kmeans                  -0.30 / -0.26
       revised_12m_k3      gmm             -0.22 / -0.28 / -0.27
                           kmeans          -0.17 / -0.29 / -0.29
       revised_12m_k4      gmm     -0.20 / -0.21 / -0.41 / -0.24
                           kmeans  -0.27 / -0.20 / -0.38 / -0.28
       revised_3m_k3       gmm             -0.36 / -0.16 / -0.21
                           kmeans          -0.38 / -0.27 / -0.22
       revised_12m_cpi_k3  gmm             -0.27 / -0.29 / -0.10
                           kmeans          -0.29 / -0.19 / -0.29
       realtime quadrants  rules   -0.42 / -0.29 / -0.33 / -0.12
       revised quadrants   rules   -0.42 / -0.32 / -0.34 / -0.12
1m     realtime_12m_k2     gmm                     -0.27 / -0.20
                           kmeans                  -0.28 / -0.25
       realtime_12m_k3     gmm             -0.28 / -0.23 / -0.35
                           kmeans          -0.28 / -0.19 / -0.28
       realtime_12m_k4     gmm      -0.38 / 0.01 / -0.17 / -0.33
                           kmeans  -0.28 / -0.37 / -0.19 / -0.28
       realtime_3m_k3      gmm             -0.10 / -0.45 / -0.35
                           kmeans          -0.26 / -0.22 / -0.46
       realtime_12m_cpi_k3 gmm             -0.22 / -0.34 / -0.10
                           kmeans          -0.26 / -0.23 / -0.29
       revised_12m_k2      gmm                     -0.31 / -0.25
                           kmeans                  -0.35 / -0.24
       revised_12m_k3      gmm             -0.24 / -0.25 / -0.32
                           kmeans          -0.17 / -0.27 / -0.33
       revised_12m_k4      gmm     -0.21 / -0.18 / -0.40 / -0.29
                           kmeans  -0.33 / -0.19 / -0.29 / -0.27
       revised_3m_k3       gmm             -0.35 / -0.15 / -0.19
                           kmeans          -0.39 / -0.26 / -0.20
       revised_12m_cpi_k3  gmm             -0.26 / -0.27 / -0.15
                           kmeans          -0.33 / -0.17 / -0.28
       realtime quadrants  rules   -0.42 / -0.27 / -0.33 / -0.11
       revised quadrants   rules   -0.42 / -0.29 / -0.35 / -0.11

GMM probabilities as continuous regressors (main run): instead of one regime per month, the probability of
each regime. Model B adds the current correlation, as in section 5.

In [24]:
probs = clusters[(MAIN, "gmm")][1].loc[ANALYSIS_START:]
for target in ["3m", "1m"]:
    y = TARGETS[target]["next"].reindex(probs.index).rename("next_corr")
    P = probs.iloc[:, 1:]                                   # first regime = reference
    for model, R in [("A", P), ("B", P.join(TARGETS[target]["current"].reindex(probs.index).rename("current_corr")))]:
        table, info = helpers.ols_hac(y, R)
        stat, p = helpers.wald_test(table, info, list(P.columns))
        print(f"\ntarget {target}, model {model}: R2 = {info['r2']:.3f}, regimes jointly p = {p:.4f}")
        print(table.round(3).drop(columns="se"))

target 3m, model A: R2 = 0.002, regimes jointly p = 0.9187
        coef      t      p
const -0.285 -4.202  0.000
p1     0.032  0.370  0.712
p2     0.030  0.379  0.705

target 3m, model B: R2 = 0.428, regimes jointly p = 0.4671
               coef      t      p
const        -0.104 -2.122  0.034
p1            0.025  0.461  0.645
p2            0.080  1.211  0.226
current_corr  0.672  9.193  0.000

target 1m, model A: R2 = 0.007, regimes jointly p = 0.5474
        coef      t      p
const -0.298 -4.918  0.000
p1     0.072  0.878  0.380
p2     0.000  0.006  0.995

target 1m, model B: R2 = 0.283, regimes jointly p = 0.3525
               coef      t      p
const        -0.163 -4.184  0.000
p1            0.069  1.440  0.150
p2            0.036  0.689  0.491
current_corr  0.530  9.759  0.000

## 2b.5 Real time against revised, and the cost of hindsight

- **Real time vs revised**: same method, the two data versions. Regimes are matched by their centres.
- **Hindsight**: the expanding-window labels against the labels of one fit on the full sample (same data).
  The gap is what a backtest built on a full-sample fit would wrongly assume was known.

In [25]:
def align_to(labels_b, centres_b, centres_a):
    order = match_labels(centres_b, centres_a)
    return labels_b.map({order[j]: j for j in range(len(order))})


for method in ["gmm", "kmeans"]:
    a_lab, _, _, a_cent = clusters[(MAIN, method)]
    b_name = MAIN.replace("realtime", "revised")
    b_lab, _, _, b_cent = clusters[(b_name, method)]
    b_al = align_to(b_lab, b_cent, a_cent)
    both = pd.DataFrame({"realtime": a_lab, "revised": b_al}).loc[ANALYSIS_START:]
    print(f"\n{method}: same regime real time vs revised in {(both.realtime == both.revised).mean():.0%} of months")
    print("2008, real time / revised:")
    print(both.loc["2008-01-31":"2009-06-30"].T.to_string())

gmm: same regime real time vs revised in 75% of months
2008, real time / revised:
          2008-01-31  2008-02-29  2008-03-31  2008-04-30  2008-05-31  2008-06-30  2008-07-31  2008-08-31  2008-09-30  2008-10-31  2008-11-30  2008-12-31  2009-01-31  2009-02-28  2009-03-31  2009-04-30  2009-05-31  2009-06-30
realtime           1           1           1           1           1           1           1           1           1           1           0           2           2           2           2           2           2           2
revised            1           1           0           0           0           0           0           0           0           0           0           2           2           2           2           2           2           2

kmeans: same regime real time vs revised in 87% of months
2008, real time / revised:
          2008-01-31  2008-02-29  2008-03-31  2008-04-30  2008-05-31  2008-06-30  2008-07-31  2008-08-31  2008-09-30  2008-10-31  2008-11-30  2008-12-31  2009-01-31  2009-02-28  2009-03-31  2009-04-30  2009-05-31  2009-06-30
realtime           1           1           1           1           1           1           1           1           1           1           0           2           2           2           2           2           2           2
revised            0           0           0           0           0           1           1           1           1           1           2           2           2           2           2           2           2           2

In [26]:
hindsight = {}
for name in [MAIN, MAIN.replace("realtime", "revised")]:
    data, horizon, with_cpi, k = RUNS[name]
    X = features(data, horizon, with_cpi)
    Xs = StandardScaler().fit_transform(X.to_numpy())
    full_fit = GaussianMixture(k, covariance_type="full", n_init=10, random_state=config.RANDOM_SEED).fit(Xs)
    full_cent = StandardScaler().fit(X.to_numpy()).inverse_transform(full_fit.means_)
    lab_full = align_to(pd.Series(full_fit.predict(Xs), index=X.index), full_cent, clusters[(name, "gmm")][3])
    lab_exp = clusters[(name, "gmm")][0]
    common = lab_exp.loc[ANALYSIS_START:].index
    hindsight[name] = (lab_exp[common] == lab_full[common]).mean()
print("expanding window vs full-sample fit, same regime:", {n: f"{v:.0%}" for n, v in hindsight.items()})

expanding window vs full-sample fit, same regime: {'realtime_12m_k3': '75%', 'revised_12m_k3': '81%'}

## 2b.6 Save

- `regimes_labels.csv`: the regime of each month, one column per run and method
- `regimes_probabilities.csv`: GMM probabilities of each regime, one block of columns per run
- `regimes_separation.csv`: the table of section 2b.4

In [27]:
labels_out = pd.DataFrame({f"{n}_{m}": c[0] for (n, m), c in clusters.items()}).rename_axis("date")
probs_out = pd.concat({n: c[1] for (n, m), c in clusters.items() if m == "gmm"}, axis=1)
probs_out.columns = [f"{a}_{b}" for a, b in probs_out.columns]
for df, name in [(labels_out, "regimes_labels"), (probs_out.rename_axis("date"), "regimes_probabilities"),
                 (separation, "regimes_separation")]:
    path = helpers.save_processed(df, name)
    print(f"saved {path.name}: {df.shape[0]} rows x {df.shape[1]} columns")

saved regimes_labels.csv: 250 rows x 20 columns
saved regimes_probabilities.csv: 250 rows x 30 columns
saved regimes_separation.csv: 44 rows x 4 columns

# Part 2c - Clustering on growth and inflation kept separate

**Why this part exists.** Part 2b, the design fixed in advance, did not separate the stock-bond correlation.
The diagnosis: PC1 mixes growth **and** inflation (all 10 indicators load on it with the same sign), so the
clusters split the months into crisis / normal / hot economy, and inflation, which drives the correlation,
ends up spread across groups. This part tests the design the diagnosis suggests, and is reported whatever it gives.

**What changes.** The features are the growth index and the inflation index of part 1 (7 and 3 indicators,
z-scores with past data only, capped at ±3), so growth and inflation stay separate by construction.
Variant: the level of CPI inflation is added. This is the like-for-like comparison with the quadrants:
same information, but the boundaries are learned from the data instead of being fixed at the past median.

**What stays the same as in 2b**: expanding window, BIC rule on data up to 2005 for the number of regimes,
warm start and label matching, K-Means and GMM, 2 and 4 regimes as robustness, real-time and revised data.

In [28]:
FIRST_COMPLETE = Z[("realtime", "12m")].index[0]   # first month with all 10 indicators (part 2a)


def index_features(data, with_cpi=False):
    X = indices[data].loc[FIRST_COMPLETE:].copy()
    if with_cpi:
        X["cpi_level"] = macro[data]["cpi"].reindex(X.index)
    return X.dropna()


bic_idx = {}
for data in ["realtime", "revised"]:
    for with_cpi in [False, True]:
        X = index_features(data, with_cpi)
        for period, Xp in [("up to 2005", X.loc[:"2005"]), ("full sample", X)]:
            b = bic_curve(Xp)
            bic_idx[(data, "indices + cpi" if with_cpi else "indices", period)] = {
                **b.round(0).to_dict(), "chosen k": choose_k(b), "months": len(Xp)}
bic_idx = pd.DataFrame(bic_idx).T
bic_idx

                                         1       2       3       4       5  \
realtime indices       up to 2005    704.0   646.0   653.0   669.0   682.0
                       full sample  2068.0  1919.0  1718.0  1721.0  1737.0
         indices + cpi up to 2005    834.0   745.0   752.0   724.0   744.0
                       full sample  2324.0  1948.0  1803.0  1698.0  1672.0
revised  indices       up to 2005    705.0   641.0   644.0   652.0   661.0
                       full sample  2080.0  1754.0  1747.0  1744.0  1754.0
         indices + cpi up to 2005    830.0   741.0   721.0   731.0   742.0
                       full sample  2341.0  1974.0  1843.0  1736.0  1707.0

                                         6  chosen k  months
realtime indices       up to 2005    695.0       2.0   120.0
                       full sample  1738.0       3.0   368.0
         indices + cpi up to 2005    754.0       4.0   120.0
                       full sample  1631.0       6.0   368.0
revised  indices       up to 2005    672.0       2.0   120.0
                       full sample  1775.0       2.0   368.0
         indices + cpi up to 2005    761.0       3.0   120.0
                       full sample  1740.0       5.0   368.0

In [29]:
K_IDX = int(bic_idx.loc[("realtime", "indices", "up to 2005"), "chosen k"])
K_IDX_CPI = int(bic_idx.loc[("realtime", "indices + cpi", "up to 2005"), "chosen k"])
print("number of regimes: indices", K_IDX, "| indices + cpi", K_IDX_CPI)

RUNS_IDX = {}   # name -> (data, with_cpi, k)
for data in ["realtime", "revised"]:
    for k in sorted({2, K_IDX, 4}):
        RUNS_IDX[f"{data}_idx_k{k}"] = (data, False, k)
    RUNS_IDX[f"{data}_idx_cpi_k{K_IDX_CPI}"] = (data, True, K_IDX_CPI)

clusters_idx = {}
for name, (data, with_cpi, k) in RUNS_IDX.items():
    X = index_features(data, with_cpi)
    for method in ["kmeans", "gmm"]:
        clusters_idx[(name, method)] = expanding_clusters(X, k, method)
    print(f"{name}: labels from {clusters_idx[(name, 'gmm')][0].index[0].date()}")

number of regimes: indices 2 | indices + cpi 4
realtime_idx_k2: labels from 2000-12-31
realtime_idx_k4: labels from 2000-12-31
realtime_idx_cpi_k4: labels from 2000-12-31
revised_idx_k2: labels from 2000-12-31
revised_idx_k4: labels from 2000-12-31
revised_idx_cpi_k4: labels from 2000-12-31

## 2c.1 What are the regimes?

In [30]:
MAIN_IDX = f"realtime_idx_k{K_IDX}"


def describe_idx(name, method):
    data, with_cpi, k = RUNS_IDX[name]
    lab = clusters_idx[(name, method)][0].loc[ANALYSIS_START:]
    df = index_features(data, True).reindex(lab.index).assign(regime=lab)
    runs = (lab != lab.shift()).cumsum()
    duration = lab.groupby(runs).size().groupby(lab.groupby(runs).first()).mean()
    out = df.groupby("regime").mean().round(2)
    out.insert(0, "months", lab.value_counts().sort_index())
    out["avg duration (months)"] = duration.round(1)
    return out


for name in [MAIN_IDX, f"realtime_idx_cpi_k{K_IDX_CPI}"]:
    for method in ["gmm", "kmeans"]:
        print(f"\n{name}, {method}:")
        print(describe_idx(name, method))

realtime_idx_k2, gmm:
        months  growth  inflation  cpi_level  avg duration (months)
regime
0          174    0.13      -0.24       2.15                   43.5
1           74   -0.79       0.53       3.43                   24.7

realtime_idx_k2, kmeans:
        months  growth  inflation  cpi_level  avg duration (months)
regime
0           29   -1.98      -1.40       0.51                    5.8
1          219    0.10       0.17       2.80                   36.5

realtime_idx_cpi_k4, gmm:
        months  growth  inflation  cpi_level  avg duration (months)
regime
0           87    0.11       0.34       2.97                    6.7
1           33   -1.87      -0.71       1.54                    5.5
2           52    0.33       0.33       3.36                    7.4
3           76    0.00      -0.35       1.89                    9.5

realtime_idx_cpi_k4, kmeans:
        months  growth  inflation  cpi_level  avg duration (months)
regime
0           29   -0.16       2.14       6.10                   14.5
1          109    0.08       0.33       3.01                    9.1
2           24   -2.24      -1.54       0.27                    8.0
3           86    0.17      -0.75       1.35                    9.6

## 2c.2 Do these regimes separate the stock-bond correlation?

Same test as in 2b.4, next to the quadrants and the main run of 2b.

In [31]:
rows = {}
for target in ["3m", "1m"]:
    for name in RUNS_IDX:
        for method in ["gmm", "kmeans"]:
            rows[(target, name, method)] = regime_test(clusters_idx[(name, method)][0].loc[ANALYSIS_START:], target)
    rows[(target, f"2b main: {MAIN}", "gmm")] = separation.loc[(target, MAIN, "gmm")].to_dict()
    for data in ["realtime", "revised"]:
        rows[(target, f"{data} quadrants", "rules")] = separation.loc[(target, f"{data} quadrants", "rules")].to_dict()
separation_idx = pd.DataFrame(rows).T
separation_idx.index.names = ["target", "run", "method"]
separation_idx

                                           R2  Wald p months  \
target run                      method
3m     realtime_idx_k2          gmm     0.001  0.7301    245
                                kmeans    0.0  0.9264    245
       realtime_idx_k4          gmm     0.128  0.0134    245
                                kmeans  0.117  0.0157    245
       realtime_idx_cpi_k4      gmm     0.067  0.0623    245
                                kmeans  0.105  0.0076    245
       revised_idx_k2           gmm     0.004  0.5523    245
                                kmeans  0.008  0.3365    245
       revised_idx_k4           gmm     0.105  0.0089    245
                                kmeans  0.164  0.0061    245
       revised_idx_cpi_k4       gmm     0.133  0.0119    245
                                kmeans  0.076  0.0402    245
       2b main: realtime_12m_k3 gmm     0.003  0.5166    245
       realtime quadrants       rules   0.144  0.0032    245
       revised quadrants        rules    0.15  0.0028    245
1m     realtime_idx_k2          gmm     0.001   0.756    247
                                kmeans  0.001   0.665    247
       realtime_idx_k4          gmm     0.073  0.0332    247
                                kmeans  0.086  0.0149    247
       realtime_idx_cpi_k4      gmm     0.049  0.0643    247
                                kmeans  0.076  0.0199    247
       revised_idx_k2           gmm       0.0  0.9583    247
                                kmeans  0.019  0.0383    247
       revised_idx_k4           gmm     0.051  0.0657    247
                                kmeans  0.113  0.0103    247
       revised_idx_cpi_k4       gmm     0.111  0.0021    247
                                kmeans  0.066  0.0387    247
       2b main: realtime_12m_k3 gmm     0.008  0.2128    247
       realtime quadrants       rules   0.109  0.0028    247
       revised quadrants        rules   0.114   0.002    247

                                                       corr by regime
target run                      method
3m     realtime_idx_k2          gmm                     -0.27 / -0.24
                                kmeans                  -0.27 / -0.26
       realtime_idx_k4          gmm     -0.38 / -0.15 / -0.16 / -0.16
                                kmeans  -0.30 / -0.30 / -0.04 / -0.33
       realtime_idx_cpi_k4      gmm     -0.17 / -0.20 / -0.33 / -0.35
                                kmeans  -0.20 / -0.18 / -0.23 / -0.40
       revised_idx_k2           gmm                     -0.28 / -0.23
                                kmeans                  -0.25 / -0.32
       revised_idx_k4           gmm     -0.37 / -0.27 / -0.33 / -0.12
                                kmeans  -0.33 / -0.05 / -0.25 / -0.36
       revised_idx_cpi_k4       gmm     -0.02 / -0.31 / -0.32 / -0.31
                                kmeans  -0.20 / -0.38 / -0.26 / -0.19
       2b main: realtime_12m_k3 gmm             -0.27 / -0.25 / -0.32
       realtime quadrants       rules   -0.42 / -0.29 / -0.33 / -0.12
       revised quadrants        rules   -0.42 / -0.32 / -0.34 / -0.12
1m     realtime_idx_k2          gmm                     -0.25 / -0.27
                                kmeans                  -0.28 / -0.25
       realtime_idx_k4          gmm     -0.36 / -0.15 / -0.14 / -0.17
                                kmeans  -0.30 / -0.33 / -0.02 / -0.31
       realtime_idx_cpi_k4      gmm     -0.15 / -0.23 / -0.31 / -0.34
                                kmeans  -0.22 / -0.15 / -0.28 / -0.38
       revised_idx_k2           gmm                     -0.25 / -0.26
                                kmeans                  -0.23 / -0.37
       revised_idx_k4           gmm     -0.34 / -0.26 / -0.31 / -0.13
                                kmeans  -0.30 / -0.04 / -0.29 / -0.37
       revised_idx_cpi_k4       gmm      0.00 / -0.31 / -0.30 / -0.35
                                kmeans  -0.21 / -0.37 / -0.30 / -0.16
       2b main: realtime_12m_k3 gmm             -0.28 / -0.23 / -0.35
       realtime quadrants       rules   -0.42 / -0.27 / -0.33 / -0.11
       revised quadrants        rules   -0.42 / -0.29 / -0.35 / -0.11

GMM probabilities of the main run as continuous regressors, as in 2b.4.

In [32]:
probs_idx = clusters_idx[(MAIN_IDX, "gmm")][1].loc[ANALYSIS_START:]
for target in ["3m", "1m"]:
    y = TARGETS[target]["next"].reindex(probs_idx.index).rename("next_corr")
    P = probs_idx.iloc[:, 1:]
    for model, R in [("A", P), ("B", P.join(TARGETS[target]["current"].reindex(probs_idx.index).rename("current_corr")))]:
        table, info = helpers.ols_hac(y, R)
        stat, p = helpers.wald_test(table, info, list(P.columns))
        print(f"\ntarget {target}, model {model}: R2 = {info['r2']:.3f}, regimes jointly p = {p:.4f}")
        print(table.round(3).drop(columns="se"))

target 3m, model A: R2 = 0.015, regimes jointly p = 0.2513
        coef      t      p
const -0.293 -5.858  0.000
p1     0.088  1.147  0.251

target 3m, model B: R2 = 0.428, regimes jointly p = 0.3234
               coef      t      p
const        -0.100 -2.777  0.005
p1            0.045  0.987  0.323
current_corr  0.663  8.966  0.000

target 1m, model A: R2 = 0.002, regimes jointly p = 0.6250
        coef      t      p
const -0.266 -5.109  0.000
p1     0.037  0.489  0.625

target 1m, model B: R2 = 0.278, regimes jointly p = 0.7150
               coef      t      p
const        -0.123 -3.821  0.000
p1            0.015  0.365  0.715
current_corr  0.530  9.809  0.000

## 2c.3 Real time against revised, 2008, and hindsight

In [33]:
for method in ["gmm", "kmeans"]:
    a_lab, _, _, a_cent = clusters_idx[(MAIN_IDX, method)]
    b_lab, _, _, b_cent = clusters_idx[(MAIN_IDX.replace("realtime", "revised"), method)]
    both = pd.DataFrame({"realtime": a_lab, "revised": align_to(b_lab, b_cent, a_cent)}).loc[ANALYSIS_START:]
    print(f"\n{method}: same regime real time vs revised in {(both.realtime == both.revised).mean():.0%} of months")
    print("2008, real time / revised:")
    print(both.loc["2008-01-31":"2009-06-30"].T.to_string())

hindsight_idx = {}
for name in [MAIN_IDX, MAIN_IDX.replace("realtime", "revised")]:
    data, with_cpi, k = RUNS_IDX[name]
    X = index_features(data, with_cpi)
    Xs = StandardScaler().fit_transform(X.to_numpy())
    full_fit = GaussianMixture(k, covariance_type="full", n_init=10, random_state=config.RANDOM_SEED).fit(Xs)
    full_cent = StandardScaler().fit(X.to_numpy()).inverse_transform(full_fit.means_)
    lab_full = align_to(pd.Series(full_fit.predict(Xs), index=X.index), full_cent, clusters_idx[(name, "gmm")][3])
    lab_exp = clusters_idx[(name, "gmm")][0]
    common = lab_exp.loc[ANALYSIS_START:].index
    hindsight_idx[name] = (lab_exp[common] == lab_full[common]).mean()
print("\nexpanding window vs full-sample fit, same regime:", {n: f"{v:.0%}" for n, v in hindsight_idx.items()})

gmm: same regime real time vs revised in 97% of months
2008, real time / revised:
          2008-01-31  2008-02-29  2008-03-31  2008-04-30  2008-05-31  2008-06-30  2008-07-31  2008-08-31  2008-09-30  2008-10-31  2008-11-30  2008-12-31  2009-01-31  2009-02-28  2009-03-31  2009-04-30  2009-05-31  2009-06-30
realtime           1           1           1           1           1           1           1           1           1           1           1           1           1           1           1           1           1           1
revised            1           1           1           1           1           1           1           1           1           1           1           1           1           1           1           1           1           1

kmeans: same regime real time vs revised in 94% of months
2008, real time / revised:
          2008-01-31  2008-02-29  2008-03-31  2008-04-30  2008-05-31  2008-06-30  2008-07-31  2008-08-31  2008-09-30  2008-10-31  2008-11-30  2008-12-31  2009-01-31  2009-02-28  2009-03-31  2009-04-30  2009-05-31  2009-06-30
realtime           1           1           1           1           1           1           1           1           1           1           1           0           0           0           0           0           0           0
revised            0           0           0           0           0           0           0           0           0           0           0           0           0           0           0           0           0           0

expanding window vs full-sample fit, same regime: {'realtime_idx_k2': '85%', 'revised_idx_k2': '93%'}

## 2c.4 Save

- `regimes_idx_labels.csv`, `regimes_idx_probabilities.csv`: as in 2b, for the index-based runs
- `regimes_idx_separation.csv`: the table of section 2c.2

In [34]:
labels_idx = pd.DataFrame({f"{n}_{m}": c[0] for (n, m), c in clusters_idx.items()}).rename_axis("date")
probs_idx_out = pd.concat({n: c[1] for (n, m), c in clusters_idx.items() if m == "gmm"}, axis=1)
probs_idx_out.columns = [f"{a}_{b}" for a, b in probs_idx_out.columns]
for df, name in [(labels_idx, "regimes_idx_labels"), (probs_idx_out.rename_axis("date"), "regimes_idx_probabilities"),
                 (separation_idx, "regimes_idx_separation")]:
    path = helpers.save_processed(df, name)
    print(f"saved {path.name}: {df.shape[0]} rows x {df.shape[1]} columns")

saved regimes_idx_labels.csv: 309 rows x 12 columns
saved regimes_idx_probabilities.csv: 309 rows x 20 columns
saved regimes_idx_separation.csv: 30 rows x 4 columns